//#include <iostream>

//#include "customexception.hpp"

//using namespace std;

//void func()
//{
//        THROW_EXCEPTION("Argument invaild!");
//}

//int main()
//{
//    try
//    {
//        func();
//    }
//    catch(CustomException& ex)
//    {
//        cout<< ex.what() << endl;
//    }

//    return 0;
//}
